### ISSUE TITLE
Support for Angular's ng-class

### ISSUE THREAD

**Issue by sagar-ganatra** [calebthebrewer/gulp-selectors#19]
The library works perfect in minimizing the class names. However, there's no way to instruct it to update class names specified in ng-class in an Angular application. 

Can this be added?

**Comment by calebthebrewer** [comment]
This can be accomplished using a custom processor with this library. I am working on a way to more easily include a customer processor since the only way to do it now is by releasing one as an npm package. Check out the [processor API](https://github.com/calebthebrewer/gulp-selectors#processors) if you're interested in adding this functionality.

**Comment by calebthebrewer** [comment]
At present I do not have the available resources to implement support for Angular's tags. For anyone interested it is possible to create a custom processor as outline in [the readme](https://github.com/calebthebrewer/gulp-selectors#processors). Hopefully I can find time to make this easier in the future but for now I will be closing this issue.
