### ISSUE TITLE
JS Processor is broken

### ISSUE THREAD

**Issue by hashworks** [calebthebrewer/gulp-selectors#7]
When I try to require the js-strings processor multiple things fail.
```js
var jsStrings = require('./node_modules/gulp-selectors/lib/processors/js-strings');
```

First:
```
Error: Cannot find module '../utils/libraries'
```
Which is due to a wrong requiring path. 

When I fix this to `libraries = require('../utils/library')` this happens:
```
var classLibrary = libraries('class').getAll(),
                                                       ^
TypeError: Cannot call method 'getAll' of undefined
```

I haven't gone any further.

**Comment by calebthebrewer** [comment]
Try using the package directly in you gulp workflow instead of requiring the libraries individually:
```js
var gulp = require('gulp');
var selectors = require('gulp-selectors');

gulp.task('default', function() {
	gulp.src(['index.html', 'style.css', 'script.js'])
		.pipe(selectors.run())
		.pipe(gulp.dest('./dist'));
});
```
The libraries aren't meant to be used separately so they haven't been tested outside of the gulp-selectors package. I'll try to add a more thorough example to the repo today or tomorrow to better demonstrate it.

**Comment by calebthebrewer** [comment]
The js string processor was never reconnected to the processor utils when I made some changes since it can be dangerous. I have updated it so it should work now, but be careful!

- It will only run on selectors which have already been processed
- It will replace string literals, there is no smart regex at work here
